### ISSUE TITLE
Importing cloudflare_zone_settings_override 

### ISSUE THREAD

**Issue by Iskhak401** [cloudflare/cf-terraforming#585] opened 2023-06-29 20:26 UTC
### Current `cf-terraforming` version

last

### Description

Currently importing cloudflare_zone_settings_override  resource not available right now? and only way is creating after generating?

### Use cases

I would like to import this cloudflare_zone_settings_override  if possible

### Potential `cf-terraforming` usage

it would be pretty good

### References

can't find any issues relating to import cloudflare_zone_settings_override

**Comment by jacobbednarz** [comment] 2023-06-30 01:05
duplicate of #313

**Closed by jacobbednarz** 2023-06-30 01:05 UTC
