### ISSUE TITLE
Can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by smcstewart** [cloudflare/cf-terraforming#594] opened 2023-08-08 09:05 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.13.0

### Expected outcome

When running `cf-terraforming version` I'm expecting that it will return the version number.

### Actual outcome

I get the attached error re: Gatekeeper not being able to open the file because is cannot be checked for malicious software. While I can workaround this easily, I would imagine it'd be nicer if the binary is notarised.

<img width="260" alt="Screenshot 2023-08-08 at 09 44 40" src="https://github.com/cloudflare/cf-terraforming/assets/5055650/48788c70-36a5-4196-b69b-8626ddbfa874">

### Steps to reproduce

1. `brew tap cloudflare/cloudflare`
2. `brew install --cask cloudflare/cloudflare/cf-terraforming`
3. `cf-terraforming version`

Or...

1. `wget https://github.com/cloudflare/cf-terraforming/releases/download/v0.13.0/cf-terraforming_0.13.0_darwin_arm64.tar.gz`
2. `shasum -a 256 cf-terraforming_0.13.0_darwin_arm64.tar.gz | echo $(grep 'cf-terraforming_0.13.0_darwin_arm64.tar.gz' checksums.txt)`
3. `tar xvzf cf-terraforming_0.13.0_darwin_arm64.tar.gz`
4. `./cf-terraforming version`

### References

No other references that I could see and I also checked Discord.

**Comment by jacobbednarz** [comment] 2023-08-08 09:12
duplicate of #309

**Closed by jacobbednarz** 2023-08-08 09:12 UTC
Labels: duplicate
