### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by andyli** [cloudflare/cf-terraforming#225] opened 2021-03-03 03:52 UTC
I cannot build cf-terraforming using the cmd suggested by README.
I'm not a go user so I'm not sure if I'm missing something obvious.

```
% GO111MODULE=on go get -u github.com/cloudflare/cf-terraforming/...
go: downloading github.com/cloudflare/cf-terraforming v0.0.0-20210212162925-e660e11f8a1a
go: found github.com/cloudflare/cf-terraforming/... in github.com/cloudflare/cf-terraforming v0.0.0-20210212162925-e660e11f8a1a
go: downloading github.com/sirupsen/logrus v1.7.0
go: downloading github.com/hashicorp/terraform-plugin-sdk v1.16.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/spf13/viper v1.7.1
go: downloading github.com/cloudflare/cloudflare-go v0.13.8
go: downloading github.com/spf13/cobra v1.1.3
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/jwalterweatherman v1.0.0
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/spf13/pflag v1.0.5
go: downloading gopkg.in/ini.v1 v1.51.0
go: downloading golang.org/x/net v0.0.0-20210119194325-5f4716e94777
go: downloading golang.org/x/time v0.0.0-20201208040808-7e3f01d25324
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: github.com/mitchellh/mapstructure upgrade => v1.4.1
go: golang.org/x/text upgrade => v0.3.5
go: github.com/pelletier/go-toml upgrade => v1.8.1
go: github.com/mitchellh/go-homedir upgrade => v1.1.0
go: gopkg.in/ini.v1 upgrade => v1.62.0
go: github.com/cloudflare/cloudflare-go upgrade => v0.14.0
go: golang.org/x/time upgrade => v0.0.0-20210220033141-f8bda1e9f3ba
go: golang.org/x/sys upgrade => v0.0.0-20210301091718-77cc2087c03b
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: golang.org/x/net upgrade => v0.0.0-20210226172049-e18ecbb05110
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/magiconair/properties upgrade => v1.8.4
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: github.com/spf13/afero upgrade => v1.5.1
go: github.com/sirupsen/logrus upgrade => v1.8.0
go: github.com/spf13/viper upgrade => v1.7.1
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/hashicorp/hcl upgrade => v1.0.0
go: downloading github.com/cloudflare/cloudflare-go v0.14.0
go: downloading github.com/sirupsen/logrus v1.8.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/pelletier/go-toml v1.8.1
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading github.com/spf13/afero v1.5.1
go: downloading github.com/magiconair/properties v1.8.4
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/mitchellh/mapstructure v1.4.1
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading golang.org/x/sys v0.0.0-20210301091718-77cc2087c03b
go: downloading golang.org/x/text v0.3.5
go: downloading github.com/magefile/mage v1.10.0
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: github.com/magefile/mage upgrade => v1.11.0
go: downloading github.com/magefile/mage v1.11.0
# github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/access_application.go:50:65: not enough arguments in call to api.ZoneLevelAccessApplications
	have (string, cloudflare.PaginationOptions)
	want (context.Context, string, cloudflare.PaginationOptions)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/access_policy.go:83:73: not enough arguments in call to api.ZoneLevelAccessApplications
	have (string, cloudflare.PaginationOptions)
	want (context.Context, string, cloudflare.PaginationOptions)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/access_policy.go:95:58: not enough arguments in call to api.ZoneLevelAccessPolicies
	have (string, string, cloudflare.PaginationOptions)
	want (context.Context, string, string, cloudflare.PaginationOptions)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/access_rule.go:56:48: not enough arguments in call to api.ListZoneAccessRules
	have (string, cloudflare.AccessRule, int)
	want (context.Context, string, cloudflare.AccessRule, int)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/account_member.go:35:47: not enough arguments in call to api.AccountMembers
	have (string, cloudflare.PaginationOptions)
	want (context.Context, string, cloudflare.PaginationOptions)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/record.go:206:53: cannot use record.Priority (type *uint16) as type int in argument to strconv.Itoa
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/record.go:208:59: cannot use record.Proxied (type *bool) as type bool in argument to strconv.FormatBool
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/root.go:194:31: not enough arguments in call to api.ZoneDetails
	have (string)
	want (context.Context, string)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/root.go:202:29: cannot use zoneName (type string) as type context.Context in argument to api.ListZones:
	string does not implement context.Context (missing Deadline method)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/root.go:216:29: not enough arguments in call to api.ListZones
	have ()
	want (context.Context, ...string)
go/pkg/mod/github.com/cloudflare/cf-terraforming@v0.0.0-20210212162925-e660e11f8a1a/internal/app/cf-terraforming/cmd/account_member.go:35:47: too many errors
```
```
% go version                                                        
go version go1.15.5 darwin/amd64
```

**Comment by andyli** [comment] 2021-03-04 05:30
I guess cloudflare-go v0.14.0 broke it.
I can build without the `-u` flag. i.e. `GO111MODULE=on go get github.com/cloudflare/cf-terraforming/...`

**Comment by Sqeegie** [comment] 2021-03-17 15:46
Looks like the issue is with the new context-awareness in v0.14.0. Blame: https://github.com/cloudflare/cloudflare-go/pull/594

**Comment by jacobbednarz** [comment] 2021-04-07 21:04
closing as a duplicate of #228

**Closed by jacobbednarz** 2021-04-07 21:04 UTC
